"""empty message

Revision ID: 3948cf551072
Revises: 
Create Date: 2026-05-01 17:40:05.911772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3948cf551072'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('user_left_notification_message',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times_voted', sa.Integer(), nullable=False),
    sa.Column('total_votes_received', sa.Integer(), nullable=False),
    sa.Column('total_feedbacks_given', sa.Integer(), nullable=False),
    sa.Column('total_feedback_words', sa.Integer(), nullable=False),
    sa.Column('total_feedbacks_received', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('total_challenges_won', sa.Integer(), nullable=False),
    sa.Column('last_submission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_purge_data', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('host_id', sa.BigInteger(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voting_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_ongoing_voting', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_challenge_id_is_active', 'challenges', ['id', 'is_active'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_feedbacks', sa.Integer(), nullable=False),
    sa.Column('total_reactions', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('idx_author_id_track_id', 'tracks', ['id', 'author_id'], unique=True)
    op.create_index('idx_track_id_channel_id', 'tracks', ['id', 'channel_id'], unique=True)
    op.create_table('feedbacks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_score', sa.Float(), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_author_thread_pairs', 'feedbacks', ['author_id', 'thread_id'], unique=True)
    op.create_index('idx_feedback_channel_id', 'feedbacks', ['id', 'channel_id'], unique=False)
    op.create_index('idx_thread_created', 'feedbacks', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_thread_id'), 'feedbacks', ['thread_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('winner_declared', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'author_id')
    )
    op.create_table('tracks_with_no_feedback',
    sa.Column('track_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('track_givers',
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', 'user_id', 'track_id')
    )
    op.create_table('votes',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('voter_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'challenge_id', 'voter_id')
    )
    op.create_index('idx_challenge_id_voter_id_submission_id', 'votes', ['challenge_id', 'voter_id', 'submission_id'], unique=False)
    op.create_table('winners',
    sa.Column('winner_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('winner_id', 'submission_id', 'challenge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    op.drop_index('idx_challenge_id_voter_id_submission_id', table_name='votes')
    op.drop_table('votes')
    op.drop_table('track_givers')
    op.drop_table('tracks_with_no_feedback')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_feedbacks_thread_id'), table_name='feedbacks')
    op.drop_index('idx_thread_created', table_name='feedbacks')
    op.drop_index('idx_feedback_channel_id', table_name='feedbacks')
    op.drop_index('idx_author_thread_pairs', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index('idx_track_id_channel_id', table_name='tracks')
    op.drop_index('idx_author_id_track_id', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('idx_challenge_id_is_active', table_name='challenges')
    op.drop_table('challenges')
    op.drop_table('users')
    op.drop_table('user_left_notification_message')
    op.drop_table('leaderboards')
    # ### end Alembic commands ###
